### PR TITLE
Add Map Book

### LINKED ISSUE #14: Add a Mapbook, a more vanilla-style atlas/minimap mod, which holds maps in a book and will swap to the correct map to show the player
Additional credits:
- Eleanor (artist of the original full mapbook texture)

Made with a Map and Book, it will start holding that map. Can be crafted with a map to add that map, and crafted with a book to clone it. Right click with paper to add a new map. Open to see all the maps stitched together into one large map, which can be zoomed and panned. UI shows markers, placed maps, and other players with the same mapbook.

### PR DESCRIPTION
**Pull request by Nettakrim**
have fun reviewing this lol

(this is a direct port from fixed, more features and tweaks will be added later - this version is pretty functional though)

(also currently it isnt configurable in any way)

### CODE REVIEW

**Comment by Flatkat** [comment]
lol. if it works im prob gonna check it as good as is (will check at code under the best of my capabilities tho lmao)

**Comment by Flatkat** [comment]
I remember a texture from eleanor i liked better tho, will try and see if i can find it hopefully

**Comment by Flatkat** [comment]
found it!
mapbook1
can we consider using this one instead? its just my personal preference though tbh. i feel like it looks more vanilla and, specially, it reflects better its use

**Comment by Flatkat** [comment]
i think theres a more up to date version of the texture tho, that looked better (im not sure). will tell ya if i find it

**Comment by Nettakrim** [comment]
yeah i just used the one from the mirror

something that would be nice is a separate version for empty map books (like the writable/signed distinction in books)

**Comment by Flatkat** [comment]
Only thing missing would be to change the recipes to cartography table ones. Ofc theres more improvements to do, but we could merge this after that change, then make more PRs improving the mapbook in the future

**Comment by Flatkat** [comment]
Found bug: when using the cartography table, putting multiple mapbooks on the first slot and a map on the second one will just "spend" one of them from the first stack, while giving the same amount as result, allowing to duplicate mapbooks

**Comment by Flatkat** [comment]
Heres two screenshots showing what i mean:
image
(on the second picture, top right bookmaps are the result from the recipe)

**Comment by Nettakrim** [comment]
im pretty sure i know exactly what the issue is there, thats funny lol

**Review by Flatkat — APPROVED** [review]
👍

**Pull request merged**
